config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/postnew', to: 'blog_posts#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/signup',  to: 'users#create'

  resources :users
  resources :categories
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :blog_posts, only: [:create, :destroy, :search]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @blog_post = current_user.blog_posts.build if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<!DOCTYPE html>

<html>
  <head>
    <title><%= yield(:title) %> | The my_blog project</title>
  </head>

  <body>
    <h1>My_blog project</h1>
  </body>
  <p>
    This is a my_blog project, a simple blog with basic blogging functions.
  </p>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  You may contact me at cacommenceamesaouler17@gmail.com.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | The my_blog project</title>
</head>
<body>
<h1>Help</h1>
<p>
  If you need any help, simply contact a moderator or the administrator.
</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <%= link_to "Post new blogpost !", postnew_path, class: "btn btn-lg btn-primary" %>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the my_blog project</h1>

    <h2>
      This is the home page for the my_blog project
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %>
<% end %>